const CONSTANTS = {
    FETCH_PRODUCTS_BEGIN: 'FETCH_PRODUCTS_BEGIN',
    FETCH_PRODUCTS_INIT: 'FETCH_PRODUCTS_INIT',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_ERROR: 'FETCH_PRODUCTS_ERROR',
    TOTAL_CHANGED: 'TOTAL_CHANGED',
};

export default CONSTANTS;